feat: ユーザー削除APIの実装
SEIZENSETSU/fleet-tracker-backend pull request #15
Opened 2024-06-22 02:34 UTC by MasayaIkeno

## 概要
ユーザー削除APIを実装しました。

## 変更点

- 要件に合うように UserController, UserService, UserRepository に追記。
- DeleteUserTest.kt を作成。

## 確認したこと
- uid に対応する User が見つからなかった際にコメントを表示する。

## リリース時に確認すること
- リリース作業時に確認することを記載してください。

2024-06-22 02:36 UTC, MasayaIkeno commented
@naruto1031 
ユーザー削除APIを実装しました。
レビューお願いします。

2024-06-23 13:50 UTC, naruto1031 approved these changes
@MasayaIkeno 
対応ありがとうございます！！
修正は任意です~~

2024-06-23 13:50 UTC, naruto1031 commented on src/main/kotlin/fleet/tracker/application_service/user/UserService.kt
> +            if (!userRepository.isUserExists(uid)) {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
ここでユーザーがいるかどうかを判定するのはとても良きです！！
ユーザーがいない場合は早期Returnしちゃいましょ！！
```suggestion
            if (!userRepository.isUserExists(uid)) {
              return ResponseEntity.status(HttpStatus.NOT_FOUND).build()
            }
```

2024-06-23 13:50 UTC, naruto1031 commented on src/test/kotlin/fleet/tracker/controller/user/DeleteUserTest.kt
> +class UserControllerDeleteTests {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
テストすばら！！

2024-06-23 13:58 UTC, naruto1031 requested changes
@MasayaIkeno 
レビューしました！！

2024-06-23 13:58 UTC, naruto1031 commented on src/main/kotlin/fleet/tracker/controller/user/UserController.kt
> +    fun deleteUser(@RequestParam("uid") uid: String): ResponseEntity<Void> {
![must-badge](https://img.shields.io/badge/review-must-red.svg)
もちろんこれでも動くのですが、レスポンスとして返す際のエラーハンドリングはControllerが責務です！(なかなか難しい) Service層では、Controllerに対してErrorをthrowするだけにしましょう！！

2024-06-24 01:09 UTC, MasayaIkeno commented
@naruto1031 
修正しました。
レビューお願いします。

2024-06-24 03:38 UTC, naruto1031 approved these changes
![LGTM](https://img.shields.io/badge/review-LGTM-green)
OKです！！

2024-06-24 03:38 UTC, naruto1031 commented
> ![LGTM](https://camo.githubusercontent.com/2ed728fc79e9a98182c9ff6817d3222d922e073e6375f3d07c1d1ceed6c98065/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f7265766965772d4c47544d2d677265656e) OKです！！

@MasayaIkeno

2024-06-24 05:06 UTC, merged