feat: ユーザー更新APIの実装
SEIZENSETSU/fleet-tracker-backend pull request #17
Opened 2024-06-24 14:16 UTC by MasayaIkeno

## 概要
ユーザー更新APIを実装しました。

## 変更点

- APIの仕様に沿うよう、Controller, Service, Repository に追記。
- UpdateUserDTO.kt、UpdateUserTest.kt を作成。

## 確認したこと
- userName と fcmTokenId のうち、新しく入力されたフィールドのみが Responce されることを確認。

## リリース時に確認すること
- リリース作業時に確認することを記載してください。

2024-06-24 14:17 UTC, MasayaIkeno commented
@naruto1031 
ユーザー更新APIを実装しました。
レビューお願いします。

2024-06-24 15:15 UTC, naruto1031 requested changes
@MasayaIkeno 
レビューしました！！自分の日本語がままならない部分があるので、わからなかったらどしどし聞いてください！！

2024-06-24 15:15 UTC, naruto1031 commented on src/main/kotlin/fleet/tracker/application_service/user/UserService.kt
> +            val response = mutableMapOf<String, String>()
![must-badge](https://img.shields.io/badge/review-must-red.svg)
Controllerで同じ処理書いちゃってるかんじなので、Controller側の処理消しちゃってください！

加えて、mutableMap周りは関数に切り出してもっと簡素にできそう
```kotlin

    fun getUpdatedFields(updateUserDTO: UpdateUserDTO): Map<String, String> {
        return mutableMapOf<String, String>().apply {
            updateUserDTO.userName?.let { this["user_name"] = it }
            updateUserDTO.fcmTokenId?.let { this["fcm_token_id"] = it }
        }
    }

    fun updateUser(uid: String, updateUserDTO: UpdateUserDTO): Map<String, String> {
        val updatedFields = getUpdatedFields(updateUserDTO)
```

2024-06-24 15:15 UTC, naruto1031 commented on src/main/kotlin/fleet/tracker/controller/user/UserController.kt
> +    fun updateUser(@RequestBody updateUserDTO: UpdateUserDTO): ResponseEntity<*> {
![must-badge](https://img.shields.io/badge/review-must-red.svg)
uidはクエリパラメータで渡すので、RequestBodyには含まれないです！(紛らわしくてすみません...)

https://seizensetsu.github.io/fleet-tracker-api-docs/swagger/
```suggestion
    fun updateUser(@RequestParam("uid") uid: String, @RequestBody updateUserDTO: UpdateUserDTO): ResponseEntity<*> {
```

2024-06-24 15:15 UTC, naruto1031 commented on src/main/kotlin/fleet/tracker/controller/user/UserController.kt
> +            val updatedFields = mutableMapOf<String, String>()
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
これらのupdateFields周りの処理は、Service層の責務のような気がします！！Service層のResponseとしてupdateFieldsを渡せると良さそう！

```suggestion
  val updatedFields = userService.updateUser(uid, updateUserDTO)
```

2024-06-24 15:15 UTC, naruto1031 commented on src/main/kotlin/fleet/tracker/controller/user/UserController.kt
> +            userService.updateUser(updateUserDTO.uid!!, updateUserDTO)
![must-badge](https://img.shields.io/badge/review-must-red.svg)
"!!"を使った強制アンラップはnullが入った時点で例外が出てしまうので、できるだけ使わないようにしましょう！！
uidが必須になるため、使わなくて良くなると思います。

2024-06-24 15:15 UTC, naruto1031 commented on src/main/kotlin/fleet/tracker/dto/UpdateUserDTO.kt
> +    val uid: String?,
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
uidは必須でよいかもです！！

2024-06-25 01:14 UTC, MasayaIkeno commented
@naruto1031 
修正しました。
レビューお願いします。

2024-06-26 04:03 UTC, naruto1031 reviewed
![LGTM](https://img.shields.io/badge/review-LGTM-green)
OKです〜

2024-06-26 04:05 UTC, naruto1031 approved these changes

2024-06-26 05:34 UTC, merged